# Generated by Django 2.0.2 on 2020-01-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='mobilenumber',
            field=models.TextField(),
        ),
    ]
