# Generated by Django 2.0.2 on 2020-01-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200104_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.TextField(),
        ),
    ]
