# Generated by Django 2.0.2 on 2020-01-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200104_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapanyname', models.TextField()),
                ('email', models.TextField()),
                ('designation', models.TextField()),
                ('address', models.TextField()),
                ('name', models.TextField()),
                ('mobilenumber', models.TextField()),
            ],
        ),
    ]
