# Generated by Django 2.0.2 on 2020-01-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='department',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='data',
            name='department',
            field=models.TextField(default='None'),
        ),
    ]
