# Generated by Django 2.0.2 on 2020-01-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message1',
            new_name='messaging1',
        ),
    ]
